name: zoonosis-risk-ml
channels:
 - conda-forge
 - bioconda
 - nodefaults
dependencies:
 - r-base=4.2
 - r-tidyverse
 - r-ggmosaic 
 - r-ggmosaic
 - r-gplots
 - r-kableExtra
 - r-knitr
 - r-lattice
 - r-magrittr
 - r-patchwork
 - r-pbapply
 - r-plotly
 - r-rentrez
 - r-reshape2
 - r-rmarkdown
 - r-R.utils
 - r-seqinr
 - r-stringr
 - r-taxizedb
 - r-tidyverse
 - r-VennDiagram
 - r-XML
 - r-caret
 - r-janitor
 - r-doparallel
 - r-glmnet
 - bioconductor-Biostrings
 - bioconductor-coRdon
 - bioconductor-ORFik
